import './globals.css'
import { Poppins } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
// import Navbar from '@/components/Navbar'
// import Banner from '@/components/Banner'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: 'DevStance - Web Dev Agency',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={poppins.className}>
        {/* <Banner /> */}
        {/* <Navbar /> */}
        <Header />
        <Hero />
        {children}
        <Footer />
      </body>
    </html >
  )
}
